name: Daily Menu Notifier

on:
  schedule:
    # 0 1 * * * -> 매일 오전 1시(KST 10시) 실행
    # 0 1 * * 1-5 -> 월,화,수,목,금 오전 1시(KST 10시) 실행
    - cron: '0 1 * * 1-5'
  workflow_dispatch:

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 사용 중인 Node 버전

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Script
        env:
          # GitHub Secrets에 등록한 변수들을 환경변수로 주입
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: node main.js
